#+AUTHOR: Karol Piera
#+email: karol.piera@unil.ch

* Description

This tool adds gene annotattion to bins. Since columns of bg2 are
2xbed3, we separate Bin1 locus information and Bin2 locus to anotate
each separately.

The output contains two columns of gene commma separated lists.

Script can be adapted to annotate bins with other features as well.


** Important

Dump output file might differ between tools and/or parameters. Make
sure your output is in bg2 format. That is: colmuns 1-3 are chrom start
end of Bin1 and columns 4-6 are chrom start end of bin2.

I use following command to generate dump:

#+begin_src bash
  hictk dump --resolution {res} --join $hic_file > dump.tsv
#+end_src

* Installation

Clone or simply copy Dump_AddGeneAnnotation.sh.

* Useage 
#+begin_src bash
  chmod +x ./Dump_AddGeneAnnotation.sh
  ./Dump_AddGeneAnnotation.sh -i [ Path to dump file] \
                              -a [ Path to gene annotation in bed format]
                              -p [ thread control, Default 15]
#+end_src

* Sample output

Output should look like this:

| chrom1 | start1 |    end1 | chrom2 |  start2 |    end2 | counts | Bin1_Genes                                                 | Bin2_Genes                                                        |
| chr1   |      0 | 1000000 | chr1   |       0 | 1000000 |   4726 | HES4,KLHL17,NOC2L,OR4F16,OR4F29,OR4F5,PERM1,PLEKHN1,SAMD11 | HES4,KLHL17,NOC2L,OR4F16,OR4F29,OR4F5,PERM1,PLEKHN1,SAMD11        |
| chr1   |      0 | 1000000 | chr1   | 1000000 | 2000000 |   2313 | HES4,KLHL17,NOC2L,OR4F16,OR4F29,OR4F5,PERM1,PLEKHN1,SAMD11 | ACAP3,AGRN,ANKRD65,ATAD3A,ATAD3B,ATAD3C,AURKAIP1,B3GALT6,C1QTNF12 |

