#+AUTHOR: Karol Piera

* Main
Collect qc from the output of hic pipeline. After hic maps are created, statistics is saved to inter.txt and inter_30.txt files.
The objective of this script is to loop over sample directories to collect metadata, clean and parse it into a usable table.

Each directory's name will be used as sample name in the table.

** Key Differences Between `inter.hic` and `inter_30.hic` in Juicer

- **inter.hic**
  - Contains all inter-chromosomal Hi-C contacts.
  - Includes contacts regardless of mapping quality (MAPQ).
  - Useful for comprehensive analysis, but includes lower-confidence alignments.

- **inter_30.hic**
  - Contains only inter-chromosomal contacts with MAPQ ≥ 30 for both read pairs.
  - Filters out lower-confidence alignments.
  - More suitable for high-confidence analysis and downstream processing.

* Usage:
Ideally there is no need to a separate environment. The tools only requires python installation with pandas + standard matplot lib and seaborn installation. 
** Create env or use
Here is an example:
#+begin_src bash
  micromamba/mamba/conda create -n hicQC
  micromamba/mamba/conda activate hicQC
  micromamba/mamba/conda install -c conda-forge python pandas matplotlib seaborn
  chmod +x Collect_inter-Stats.sh make_barplt.py
#+end_src

** Run
#+begin_src bash
    ./Collect_inter-Stats.sh -i <hic_pipeline_output_directory> \
    			 -o <output_dir> \ # Will be created if does not exist
                             -l <label> # Label for the tables that will be created. eg. 2025-04-12_WGD_CPA
   # Sample out put will look like this
  drwxrwxr-x. 2 4096 Apr 29 12:37 plots
  -rw-rw-r--. 1  655 Apr 29 12:36 prostate_Stats_MAPQ30-filtered.csv
  -rw-rw-r--. 1  655 Apr 29 12:36 prostate_Stats_unfiltered.csv
   
#+end_src

** Output

*** Default Extracted statistics:
- UniqueReads
- Intra-fragmentReads
- NormalPaired
- Intra-chromosomal
- PCRDuplicates
- Inter-chromosomal
- OpticalDuplicates
- Hi-CContacts
- SequencedReadPairs
The list can be extended upon request.
*** Plots
Here you can find qc metric plots for each statistic extracted.

*** Master tables
Two csv files: <label>_MAPQ30-filtered.csv and <label>_unfiltered.csv contain all sample-level statistics for filtered and unfiltered data.

