
Small tool to extract QC from Hi-C maps in hic format (cool support soon) in a convenient way.

* Installation

Use conda / mamba to install dependencies from the environment.yml
file.
If you have a working environment with hictk, polars, pandas and  matplotlib and seaboorn you might ignore this step.
  
#+begin_src bash
    conda env create -f environment.yml -n hictk
    activate GetHiCStats
#+end_src

* Useage

Script takes a DIRECTORY as an input.
Currently, it supports two scenarios:
- A directory containing Hi-C maps in .hic format (will loop over files)
- A directory with sub-directories containing inter_30.hic maps as
  return by the Hi-C juicer pipeline. In this case it will loop over
  sub-directories

* Output

**  meta.clean.csv output file
This is the main output file.
- Sample: The name of the sample (file name or subdirectory name)
- Hi-C TotalUnique Contacts: The total number of unique Hi-C contacts in the map
- Hi-C TotalDuplicates: The total number of duplicate Hi-C contacts in the map
- Hi-C Contacts: The total number of Hi-C contacts in the map
- Hi-C Inter-chromosomal Contacts: The total number of inter-chromosomal Hi-C contacts in the map
- Hi-C Intra-chromosomal Contacts: The total number of intra-chromosomal Hi-C contacts in the map

** Plots
- A bar plot for each metric in the metadata file.
- AC report is a merged pdf of all the plots.

* Example

This is an example that you can actually run if you want to test (works on electron, positron, neutrino).

#+begin_src bash
  chmod +x ./src/Main.sh
  ./src/Main.sh -i /mnt/etemp/karol/data/atlas_work/hicMaps_forTest -o ./output
#+end_src


* Note

Other statistics can be added by modifying the program if needed. Contact me for help.

To modify plotting function change 1.pl-QCmetrics.py

WARNING!!! > there is no guarantee of hictk metadata actually being in the hic file. The script will work for SURE for:
- Hi-C files generated with juicer hic pipeline
- ENCODE hic files
- 4DN hic files

If hic files comes from a tool conversion or liftover I'm not sure if it works.
